<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 15/09/2018
 * Time: 3:05 AM
 */

?>
<li>
    <a href="<?php echo $url->database;?>">
        <i class="ti-user"></i>
        <p><?php echo $button->database;?></p>
    </a>
</li>
<li>
    <a href="table.html">
        <i class="ti-view-list-alt"></i>
        <p>Table List</p>
    </a>
</li>
<li>
    <a href="typography.html">
        <i class="ti-text"></i>
        <p>Typography</p>
    </a>
</li>
<li>
    <a href="icons.html">
        <i class="ti-pencil-alt2"></i>
        <p>Icons</p>
    </a>
</li>
<li>
    <a href="maps.html">
        <i class="ti-map"></i>
        <p>Maps</p>
    </a>
</li>
<li>
    <a href="<?php echo $url->mining;?>">
        <i class="ti-shortcode"></i>
        <p><?php echo $button->mining;?></p>
    </a>
</li>
