<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 15/09/2018
 * Time: 3:40 AM
 */
?>
<li>
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="ti-panel"></i>
        <p>Stats</p>
    </a>
</li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="ti-bell"></i>
        <p class="notification">5</p>
        <p>Notifications</p>
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        <li><a href="#">Notification 1</a></li>
        <li><a href="#">Notification 2</a></li>
        <li><a href="#">Notification 3</a></li>
        <li><a href="#">Notification 4</a></li>
        <li><a href="#">Another notification</a></li>
    </ul>
</li>
<li>
    <a href="#">
        <i class="ti-settings"></i>
        <p>Settings</p>
    </a>
</li>
<li>
    <a href="#">
        <i class="ti-power-off"></i>
        <p>Exit</p>
    </a>
</li>
