<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 13/09/2018
 * Time: 7:11 AM
 */
?>
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title><?php echo $template->tilte;?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Coupled Login Form Bootstrap Responsive Templates, Iphone Compatible Templates, Smartphone Compatible Templates, Ipad Compatible Templates, Flat Responsive Templates"/>
    <link rel="shortcut icon" href="../assets/images/atom-128x128.png" type="image/x-icon">
    <link href="../plugin/web/css/style.css" rel='stylesheet' type='text/css' />
    <!--webfonts-->
    <link href="//fonts.googleapis.com/css?family=Montserrat:400,600,700,800,900" rel="stylesheet">
    <!--//webfonts-->
</head>
<body>
<!-- section -->
<section class="register">

    <div class="register-left">
        <div class="register-in">
            <h3>Please Login Here</h3>
            <form method="post" action="login.php" enctype="multipart/form-data">
                <div class="fields-grid">
                    <div class="styled-input agile-styled-input-top">
                        <input type="text" name="username" required="">
                        <label>User Name</label>
                        <span></span>
                    </div>
                    <div class="styled-input">
                        <input type="password" name="password" required="">
                        <label>Password</label>
                        <span></span>
                    </div>
                    <div class="clear"> </div>
                </div>
                <div class="w3_lgn">
                    <input type="submit" name="submit" value="login">
                </div>
            </form>
        </div>
    </div>
    <div class="register-right">
        <div class="register-in">
            <h2>Subscribe Here</h2>
            <p>To Get Our News Updates Please Enter Your Mail ID Here</p>
            <div class="register-form">
                <form action="login.php" method="post" enctype="multipart/form-data">
                    <div class="fields-grid">
                        <div class="styled-input">
                            <input type="email" name="email" required="">
                            <label>Email</label>
                            <span></span>
                        </div>
                        <div class="clear"> </div>
                    </div>
                    <div class="w3_lgn1">
                        <input type="submit" name="submit" value="sign up">
                    </div>
                </form>
            </div>
        </div>
        <div class="clear"> </div>
    </div>
    <div class="clear"> </div>

    <!-- copyright -->
    <p class="agile-copyright">&copy  2015 - 2018 Cosmos Reactor. All Rights Reserved | Powered by <a href="#" target="_blank">iQuipe Digital</a></p>
    <!-- //copyright -->
</section>
<!-- //section -->

</body>
</html>
